name: test
on: [push]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Format check
        run: gofumpt -l .

      - name: Test
        run: make test
